FLASK: # These are Flask configuration settings
  HOST: 0.0.0.0
  PORT: '5000'
  SECRET: abcd1234 
  DEBUG: false
  TEMPLATES_AUTO_RELOAD: true
  USE_RELOADER: false
  LOGIN_DISABLED: false # this one disables authentication (login access control)

SITE:
  BASE_URL: http://localhost # this is your domain or start of your url 
  PATH_PREFIX: / # this is useful if you want a prefix on the url path. eg: /where

USERS: # users for flask-login - will be updated with settings... eg: if you change your sorting
  1:
    username: user
    password: pass
  2:
    username: user2
    password: pass
